# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dense_pb2 as dense__pb2


class PredictStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict_nsfw = channel.unary_unary(
                '/dense.Predict/predict_nsfw',
                request_serializer=dense__pb2.ImageData.SerializeToString,
                response_deserializer=dense__pb2.Response.FromString,
                )
        self.predict_logo = channel.unary_unary(
                '/dense.Predict/predict_logo',
                request_serializer=dense__pb2.ImageData.SerializeToString,
                response_deserializer=dense__pb2.Response.FromString,
                )


class PredictServicer(object):
    """Missing associated documentation comment in .proto file"""

    def predict_nsfw(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def predict_logo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict_nsfw': grpc.unary_unary_rpc_method_handler(
                    servicer.predict_nsfw,
                    request_deserializer=dense__pb2.ImageData.FromString,
                    response_serializer=dense__pb2.Response.SerializeToString,
            ),
            'predict_logo': grpc.unary_unary_rpc_method_handler(
                    servicer.predict_logo,
                    request_deserializer=dense__pb2.ImageData.FromString,
                    response_serializer=dense__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dense.Predict', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Predict(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def predict_nsfw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dense.Predict/predict_nsfw',
            dense__pb2.ImageData.SerializeToString,
            dense__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def predict_logo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dense.Predict/predict_logo',
            dense__pb2.ImageData.SerializeToString,
            dense__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
