# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dense.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dense.proto',
  package='dense',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x64\x65nse.proto\x12\x05\x64\x65nse\"\x1b\n\tImageData\x12\x0e\n\x06postId\x18\x01 \x01(\t\":\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0e\n\x06isNext\x18\x03 \x01(\x08\x32\xac\x01\n\x07Predict\x12\x33\n\x0cpredict_nsfw\x12\x10.dense.ImageData\x1a\x0f.dense.Response\"\x00\x12\x33\n\x0cpredict_logo\x12\x10.dense.ImageData\x1a\x0f.dense.Response\"\x00\x12\x37\n\x10predict_pipeline\x12\x10.dense.ImageData\x1a\x0f.dense.Response\"\x00\x62\x06proto3'
)




_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='dense.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='postId', full_name='dense.ImageData.postId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='dense.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dense.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='dense.Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isNext', full_name='dense.Response.isNext', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'dense_pb2'
  # @@protoc_insertion_point(class_scope:dense.ImageData)
  })
_sym_db.RegisterMessage(ImageData)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'dense_pb2'
  # @@protoc_insertion_point(class_scope:dense.Response)
  })
_sym_db.RegisterMessage(Response)



_PREDICT = _descriptor.ServiceDescriptor(
  name='Predict',
  full_name='dense.Predict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=112,
  serialized_end=284,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict_nsfw',
    full_name='dense.Predict.predict_nsfw',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='predict_logo',
    full_name='dense.Predict.predict_logo',
    index=1,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='predict_pipeline',
    full_name='dense.Predict.predict_pipeline',
    index=2,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICT)

DESCRIPTOR.services_by_name['Predict'] = _PREDICT

# @@protoc_insertion_point(module_scope)
